### ISSUE TITLE
Abnormal behavior when swiping left or right 

### ISSUE THREAD

**Issue by barakshr** [qaprosoft/carina#637]
We encounter different behavior then expected when using the 
MobileUtils.swipeLeft( element , int) / MobileUtils.swipeRight(element , int) .
it was used on an android emulator .
we have an internal small app with  a button that can be dragged left /right 
when swiping right, the button  only reached till 50% of the screen
and after that, when we swipe left the button jump left and started to move from there 

happened in 6.06

**Comment by vdelendik** [comment]
@barakshr, could you please re-test using 6.0.9?
After talking with mobile automation engineers they also suggest to play with coordinates for your app. Basically swipe left/right works fine. 

2. Also, as I see you do swipe in container as element is used as 1st argument. Is it refer to the scrollable part of the application?

3. Anyway to record video?

**Comment by kolyakrasnik** [comment]
@barakshr Swipe left/right uses coordinates of your element. As far as your element is changeable, you have to be sure that returned element's coordinates are correct. Also you can try to add '@DisableCacheLookup' annotation to your element. This will cause re-finding of your changeable element and its coordinates.  
You can also try to play with `public static void swipe(int startx, int starty, int endx, int endy, int duration)` method. Also, try to adjust 'duration' parameter for your purposes.

**Comment by alonhartman** [comment]
Hi,
We are using the `MobileUtils.swipeRight(element)` and `MobileUtils.swipeLeft(element)` in order to fill bars in a mobile application (e.g. rating bar).
I attached 2 log files (console and appium) and a video recording of the 2 actions (first the 'swipeRight' and second the 'swipeLeft'.
[appiumLogs.txt](https://github.com/qaprosoft/carina/files/2856005/appiumLogs.txt)
[consoleLogs.txt](https://github.com/qaprosoft/carina/files/2856006/consoleLogs.txt)
[video_swipeRightAndLeft.zip](https://github.com/qaprosoft/carina/files/2856017/video_swipeRightAndLeft.zip)

when I'm trying to use the `MobileUtils.swipe(startX, startY, endX, endY, 1000);` (X/Y calculations are done my me) it works well.

**Comment by kolyakrasnik** [comment]
Hi, @alonhartman! It is expected behavior for this method. We use the next logic in swipeLeft/swipeRight
`if (os.equalsIgnoreCase(SpecialKeywords.ANDROID)) {
            minCoefficient = 0.25;
            maxCoefficient = 0.5;
}`
So we multiply our element's coordinates to minCoefficient and maxCoefficient. The purpose of this method is to move inside the element (container).
What you need  - is not moving inside the element. My suggestion is to implement your own method to interact with slider.
