### ISSUE TITLE
move cucumber reports outside of artifacts

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#816]
publishReport('**/artifacts/**', 'Artifacts')
publishReport('**/artifacts/**/feature-overview.html', 'CucumberReport')

1st line publish all cucumber items as dedicated files... need separate artifacts and Cucumber Reports folders

**Comment by SergeiZagriychuk** [comment]
carina version: 7.0.0-SNAPSHOT

how to reproduce:
- execute cucumber tests with carina-cucumber module (need to use one with latest cucumber improvements in order to get proper cucumber report)
- open emailable test report at "project\reports\qa\emailable-report.html"
- there is "Open Cucumber Report in new Window" link should present in report and it should refer to path like "...../cucumber-reports/cucumber-html-reports/overview-features.html" instead of "artifacts/cucumber-html-reports/overview-features.html"
